name: Spring Service
run-name: Deploy ${{ github.ref_name }} to ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: test
      action:
        description: "Choose what to do"
        required: true
        type: choice
        options:
          - build-only
          - build-and-deploy
        default: build-and-deploy
  push:
    paths:
      - 'apps/spring-service'

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: [self-hosted, nuc-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        working-directory: apps/spring-service
        run: ./gradlew test

  build-docker:
    name: Build Docker Image
    runs-on: [self-hosted, nuc-runner]
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Populate properties file
        working-directory: apps/spring-service
        run: |
          BASE_DIR="/opt/nuc-apps/spring-service"
          RESOURCES_DIR="${BASE_DIR}/resources"
          PROPERTIES_FILE="application-${{ github.event.inputs.environment }}.properties"
          
          echo "Copying 'application.properties' into directory: $RESOURCES_DIR"
          cp "./src/main/resources/application.properties" "$RESOURCES_DIR/application.properties"
          
          echo "Copying '$PROPERTIES_FILE' into directory: $RESOURCES_DIR"
          cp "./src/main/resources/$PROPERTIES_FILE" "$RESOURCES_DIR/$ENV_FILE"

          chown sonic:sonic -R "$RESOURCES_DIR"
          chmod 600 "$RESOURCES_DIR/application.properties"
          chmod 600 "$RESOURCES_DIR/$PROPERTIES_FILE"

          sed -i "s|\${POSTGRES_DB}|${{ vars.POSTGRES_DB }}|g" "$RESOURCES_DIR/$PROPERTIES_FILE"
          sed -i "s|\${POSTGRES_USER}|${{ vars.POSTGRES_USER }}|g" "$RESOURCES_DIR/$PROPERTIES_FILE"
          sed -i "s|\${POSTGRES_PASSWORD}|${{ secrets.POSTGRES_PASSWORD }}|g" "$RESOURCES_DIR/$PROPERTIES_FILE"

      - name: Docker build
        working-directory: apps/spring-service
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          echo "Building version: $VERSION"
          docker build -t spring-service:${VERSION} .

  deploy:
    name: Start Docker Container
    runs-on: [self-hosted, nuc-runner]
    needs: [run-tests, build-docker]
    if: ${{ github.event.inputs.action == 'build-and-deploy' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker compose stop
        working-directory: apps/spring-service
        run: |
          docker compose stop spring-service || true
          docker compose rm -f spring-service || true

      - name: Docker compose up
        working-directory: apps/spring-service
        env:
          VERSION: ${{ github.ref_name }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          COMMIT: ${{ github.sha }}
        run: |
          echo "Deploying version '$VERSION' to environment '$ENVIRONMENT'"
          echo "Commit sha '${COMMIT}'"
          docker compose up -d --build spring-service
